{% set name = "jupyterlab-filesystem-access" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ef1061f2291519d5089fb3442bd7839a89cb30d64d00b928f39613acee8fc89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python  >=3.6
    - pip
    - jupyterlab
    - yarn
    - jupyter-packaging
  run:
    - python  >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-filesystem-access/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-filesystem-access\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access
  summary: Mount local folder in JupyterLab using the Filesystem API
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://jupyterlab-filesystem-access.readthedocs.io
  dev_url: https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access

extra:
  recipe-maintainers:
    - martinRenou
    - jtpio
